# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  dotnetdemo1:
    image: dotnetdemo1
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8081:8081
